const assert = require('node:assert/strict');
const { matchesSearch, categoryOf } = require('../../static/js/googleplex_search_presentation');
const tool = { name: 'GX', type: 'tracker', map_actions: ['atm_logs'], description: 'Custom tool' };
const camera = { name: 'Hold', map_actions: ['camera_shutdown'] };
const ticket = { name: 'Berlin', product_type: 'travel_ticket', effects: [{type: 'travel_city', city: 'Berlin'}] };
assert(matchesSearch(tool, 'narzędzia bankomat'));
assert(matchesSearch(tool, 'BANKOMAT narzedzie'));
assert(matchesSearch(camera, 'wyłączenie kamery'));
assert(!matchesSearch(tool, 'kamery'));
assert(!matchesSearch(tool, '/all', 'travel_ticket'));
assert(matchesSearch(ticket, 'bilety Berlin', 'travel_ticket'));
assert(matchesSearch(ticket, 'travel city'));
assert(matchesSearch({ product_type: 'storage_upgrade' }, 'pamięć dysk'));
assert(matchesSearch({ product_type: 'scan_upgrade' }, 'zasięg mapy'));
assert(matchesSearch({ product_type: 'bike_upgrade' }, 'motocykl'));
assert(matchesSearch({template_id: 'ptk_document'}, 'dokumenty', 'documents'));
assert.equal(categoryOf({ product_type: 'future_product' }), 'other');
assert.equal(categoryOf(tool), 'tools');
assert(!matchesSearch(null, '/all'));
assert(matchesSearch(tool, '  ', 'tools'));
console.log('Googleplex category/search tests: OK');
